# Generated by Django 3.1.4 on 2021-02-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Voting'), (2, 'End'), (3, 'Deleted')], default=0),
        ),
    ]
