# Generated by Django 3.1.4 on 2021-02-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210216_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Voting'), (2, 'End'), (3, 'Deleted')], default=0),
        ),
    ]
