# Generated by Django 3.1.4 on 2021-02-18 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0004_auto_20210216_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_in_question', to='first_app.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_in_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
